name: SplitPDF
options:
  bundleIdPrefix: com.splitpdf
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"

settings:
  base:
    SWIFT_VERSION: "5.0"
    MACOSX_DEPLOYMENT_TARGET: "13.0"
  configs:
    Debug:
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: N8TV6E2M4Y
      CODE_SIGN_IDENTITY: "Apple Development"
    Release:
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: N8TV6E2M4Y
      CODE_SIGN_IDENTITY: "Apple Development"

targets:
  SplitPDF:
    type: application
    platform: macOS
    sources:
      - path: SplitPDF
        excludes:
          - "**/.DS_Store"
      - path: Shared
        excludes:
          - "**/.DS_Store"
    dependencies:
      - sdk: PDFKit.framework
      - sdk: UserNotifications.framework
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.splitpdf.app
        INFOPLIST_FILE: SplitPDF/Info.plist
        CODE_SIGN_STYLE: Automatic
        COMBINE_HIDPI_IMAGES: YES
        LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - "@executable_path/../Frameworks"
