name: SplitPDF
options:
  bundleIdPrefix: com.splitpdf
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"

settings:
  base:
    SWIFT_VERSION: "5.0"
    MACOSX_DEPLOYMENT_TARGET: "13.0"

targets:
  SplitPDF:
    type: application
    platform: macOS
    sources:
      - path: SplitPDF
        excludes:
          - "**/.DS_Store"
      - path: Shared
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.splitpdf.app
        INFOPLIST_FILE: SplitPDF/Info.plist
        CODE_SIGN_STYLE: Automatic
        COMBINE_HIDPI_IMAGES: YES
        LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - "@executable_path/../Frameworks"
    dependencies:
      - target: SplitPDFExtension
        embed: true
        codeSign: true
        buildPhase:
          copyFiles:
            destination: pluginsAndFoundation

  SplitPDFExtension:
    type: app-extension
    platform: macOS
    sources:
      - path: SplitPDFExtension
        excludes:
          - "**/.DS_Store"
      - path: Shared
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.splitpdf.app.extension
        INFOPLIST_FILE: SplitPDFExtension/Info.plist
        CODE_SIGN_STYLE: Automatic
        SKIP_INSTALL: YES
        LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - "@executable_path/../Frameworks"
          - "@executable_path/../../../../Frameworks"
